server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.security.oauth2: DEBUG

spring:
  application:
    name: portal-app
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: on
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks

grpc:
  client:
    user-app:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 8091
