version: '3'

services:
  yj-consul-server:
    image: consul
    container_name: yj-consul-server
    restart: on-failure
    ports:
      - 18500:18500
      - 8600:8600/udp
    command: agent -server -ui -node=server -bootstrap-expect=1 -client=0.0.0.0 -http-port=18500
    networks:
      - yjnet

  yj-consul-client:
    image: consul
    container_name: yj-consul-client
    restart: on-failure
    depends_on:
      - yj-consul-server
    ports:
      - 8500:8500
    command: agent -node=client -join=yj-consul-server -client=0.0.0.0
    networks:
      - yjnet

  yj-postgres:
    container_name: yj-postgres
    build:
      context: ./software/postgres
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: YJ.2020
    volumes:
      - ./var/postgresql:/var/lib/postgresql
    networks:
      - yjnet

  yj-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: yj-elasticsearch
    restart: on-failure
    user: elasticsearch
    environment:
      - cluster.name=yj-elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # mkdir -p ./var/elasticsearch/data; sudo chown -R 1000:1000 ./var/elasticsearch/data
      - ./var/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - yjnet

  yj-kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: yj-kibana
    depends_on:
      - yj-elasticsearch
    restart: on-failure
    environment:
      SERVER_NAME: yj-kibana
      ELASTICSEARCH_HOSTS: http://yj-elasticsearch:9200
    #    volumes:
    #      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - yjnet

  yj-apm-server:
    image: docker.elastic.co/apm/apm-server:7.10.0
    container_name: yj-apm-server
    depends_on:
      - yj-elasticsearch
    restart: on-failure
    user: apm-server
#    environment:
#      - output.elasticsearch.hosts="yj-elasticsearch:9200"
    volumes:
      - ./software/apm-server/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - yjnet

  yj-pulsar:
    image: apachepulsar/pulsar:2.6.2
    container_name: yj-pulsar
    restart: on-failure
    command: "bin/pulsar standalone"
    volumes:
      - ./var/pulsar/data:/pulsar/data
#      - ./var/pulsar/conf:/pulsar/conf
    ports:
      - 6650:6650
      - 8080:8080
    networks:
      - yjnet

#  yj-zookeeper:
#    container_name: yj-zookeeper
#    image: zookeeper:3.5
#    restart: on-failure
#    ports:
#      - "2181:2181"
#    networks:
#      - yjnet

#  yj-kafka:
#    container_name: yj-kafka
#    image: wurstmeister/kafka:2.12-2.5.1
#    depends_on:
#      - yj-zookeeper
#    restart: on-failure
#    ports:
#      - "9092:9092"
#      - "9988:9988"
#    environment:
#       #若需要在其它物理主机上访问此Kafka服务，此处应设置为物理主机实际IP地址
#      KAFKA_ADVERTISED_HOST_NAME: "localhost"
#      #KAFKA_CREATE_TOPICS: "test:1:1"
#      KAFKA_ZOOKEEPER_CONNECT: yj-zookeeper:2181
#      JMX_PORT: 9988
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - yjnet

networks:
  yjnet:
