### Get user by id.
GET http://{{host}}:8090/api/user/get/1
Accept: application/json
Authorization: Bearer eyJraWQiOiI1ZmM4YTAxNDAxMDAwMDAxMDAxNjM2ZWMiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJlYy1jbGllbnQiLCJzY29wZSI6Im1lc3NhZ2UucmVhZCBhcGkucmVhZCIsImlzcyI6Imh0dHBzOlwvXC9ha2thLXNlY3VyaXR5LmhlbGxvc2NhbGEuY29tIiwiZXhwIjoxNjA3NTkwMzExLCJpYXQiOjE2MDY5ODUyMTEsImp0aSI6IjVmYzhhMDE0MDEwMDAwMDEwMDE2MzZlYyJ9.a5B22PZKOJS00BVyubMoHkr8EFcJFPIDEdz3YxG_aev3eRPg1V-_myZYejqOo2-O79dSGzsGNtbZqrZecr1K0A

###
POST http://{{host}}:8090/messages/sayHello
Content-Type: application/json
Authorization: Bearer eyJraWQiOiI1ZmM4YTAxNDAxMDAwMDAxMDAxNjM2ZWMiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJlYy1jbGllbnQiLCJzY29wZSI6Im1lc3NhZ2UucmVhZCBhcGkucmVhZCIsImlzcyI6Imh0dHBzOlwvXC9ha2thLXNlY3VyaXR5LmhlbGxvc2NhbGEuY29tIiwiZXhwIjoxNjA3NTkwMzExLCJpYXQiOjE2MDY5ODUyMTEsImp0aSI6IjVmYzhhMDE0MDEwMDAwMDEwMDE2MzZlYyJ9.a5B22PZKOJS00BVyubMoHkr8EFcJFPIDEdz3YxG_aev3eRPg1V-_myZYejqOo2-O79dSGzsGNtbZqrZecr1K0A

{"name": "杨景"}
